// <auto-generated />
using Heart_Disease_Prediction.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Heart_Disease_Prediction.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Heart_Disease_Prediction.Models.entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Age")
                        .HasColumnType("real");

                    b.Property<float>("Ca")
                        .HasColumnType("real");

                    b.Property<float>("Chol")
                        .HasColumnType("real");

                    b.Property<float>("Cp")
                        .HasColumnType("real");

                    b.Property<float>("Exang")
                        .HasColumnType("real");

                    b.Property<float>("Fbs")
                        .HasColumnType("real");

                    b.Property<bool>("Label")
                        .HasColumnType("bit");

                    b.Property<float>("OldPeak")
                        .HasColumnType("real");

                    b.Property<bool>("Prediction")
                        .HasColumnType("bit");

                    b.Property<float>("Probability")
                        .HasColumnType("real");

                    b.Property<float>("RestEcg")
                        .HasColumnType("real");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.Property<float>("Sex")
                        .HasColumnType("real");

                    b.Property<float>("Slope")
                        .HasColumnType("real");

                    b.Property<float>("Thal")
                        .HasColumnType("real");

                    b.Property<float>("Thalac")
                        .HasColumnType("real");

                    b.Property<float>("TrestBps")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("states");
                });
#pragma warning restore 612, 618
        }
    }
}
